apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: webapp
  type: LoadBalancer
status:
  loadBalancer: {}
