apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: shakhawat3111/webserver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/gitcreds
    argocd-image-updater.argoproj.io/git-branch: main
  name: kustomize
  namespace: argocd
spec:
  destination:
    namespace: kustomize
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomization
    repoURL: https://github.com/shakhawat-devops/argocd.git
    targetRevision: HEAD
