apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: webapp-pod
  name: web-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    name: webapp-pod
  type: NodePort
status:
  loadBalancer: {}
